In [1]:
import matplotlib.pyplot as plt 
import numpy as np
from sklearn import datasets,linear_model,preprocessing
from sklearn.svm import SVC
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
# load the datasets
prices = datasets.load_boston()

In [3]:
prices['data']

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [4]:
#look at the available features
prices.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [5]:
#using data feature [ all data first:last,:column,float format]
prices_X = prices.data[:,np.newaxis, 2]

In [6]:
#split data into training and test data
prices_X_train = prices_X[:-20]
prices_X_test = prices_X[-20:]

In [7]:
#split target into training and test data
prices_y_train = prices.target[:-20]
prices_y_test = prices.target[-20:]

In [8]:
#creating linear regression object
regr = SVC()

In [9]:
prices_X_train

array([[ 2.31],
       [ 7.07],
       [ 7.07],
       [ 2.18],
       [ 2.18],
       [ 2.18],
       [ 7.87],
       [ 7.87],
       [ 7.87],
       [ 7.87],
       [ 7.87],
       [ 7.87],
       [ 7.87],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 5.96],
       [ 5.96],
       [ 5.96],
       [ 5.96],
       [ 2.95],
       [ 2.95],
       [ 6.91],
       [ 6.91],
       [ 6.91],
       [ 6.91],
       [ 6.91],
       [ 6.91],
       [ 6.91],
       [ 6.91],
       [ 6.91],
       [ 5.64],
       [ 5.64],
       [ 5.64],
       [ 5.64],
       [ 4.  ],
       [ 1.22],
       [ 0.74],
       [ 1.32],
       [ 5.13],
       [ 5.13],
       [ 5.13],
       [ 5.13],
       [

In [10]:
label_encoder = preprocessing.LabelEncoder()
training_score_encoded = label_encoder.fit_transform(prices_y_train)
test_score_encoded = label_encoder.fit_transform(prices_y_test)

In [11]:
training_score_encoded

array([136, 112, 195, 192, 202, 164, 125, 155,  63,  86,  51,  86, 113,
       101,  79,  96, 127,  72,  99,  79,  39,  93,  53,  47,  56,  41,
        64,  49,  81, 107,  31,  47,  35,  34,  38,  86,  97, 107, 143,
       175, 196, 152, 148, 143, 109,  90,  97,  64,  46,  91,  94, 102,
       145, 130,  86, 199, 143, 180, 129,  93,  84,  58, 118, 145, 188,
       131,  91, 116,  71, 106, 138, 113, 124, 130, 137, 110,  97, 105,
       109, 100, 158, 135, 144, 125, 135, 152, 121, 118, 132, 164, 122,
       116, 125, 145, 103, 161, 110, 210, 218, 190, 156, 151,  83,  90,
        98,  92,  92, 101,  95,  91, 113, 124,  85,  84,  82,  80, 109,
        89, 101,  90, 116, 100, 102,  70,  85, 110,  57,  60,  77,  45,
        89,  93, 126,  81,  56,  78,  71,  68,  36,  75,  42,  46,  37,
        56,  24,  40,  56,  48,  75,  55, 111,  93,  54,  91,  67,  56,
        34, 212, 139, 129, 154, 227, 227, 227, 123, 145, 227, 134, 134,
       119,  71,  88, 127, 132, 122, 167, 128, 142, 170, 206, 21

In [12]:
# Train the model using the training sets
regr.fit(prices_X_train,training_score_encoded)

/usr/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [13]:
#prediction using test data
prices_y_pred = regr.predict(prices_X_test)

In [14]:
prices_y_pred

array([227, 227, 227, 227, 227, 227, 227, 124, 124, 124, 124, 124, 124,
       124, 124, 113, 113, 113, 113, 113])

In [15]:
test_score_encoded

array([ 8, 11,  4,  0,  1,  3, 10, 13, 18, 16,  9,  7, 12,  6,  5, 15, 11,
       17, 14,  2])

In [16]:
mean_squared_error(prices_y_test,prices_y_pred)

22225.647000000004

In [17]:
from sklearn.metrics import accuracy_score

accuracy_score(prices_y_pred, test_score_encoded)

0.0